import React, { useEffect } from 'react';
import '../styles/LandingPage.css';
import { ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

const TermsOfService = () => {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    return (
        <div className="terms-page" style={{
            backgroundColor: '#0a0a14',
            minHeight: '100vh',
            color: 'var(--text-primary)',
            padding: '4rem 2rem'
        }}>
            <div className="max-w-4xl mx-auto" style={{ maxWidth: '900px', margin: '0 auto' }}>
                <div className="mb-8">
                    <Link to="/" className="inline-flex items-center gap-2 text-accent hover:text-accent-2 transition-colors" style={{
                        color: 'var(--accent)',
                        display: 'inline-flex',
                        alignItems: 'center',
                        gap: '0.5rem',
                        marginBottom: '2rem',
                        textDecoration: 'none'
                    }}>
                        <ArrowLeft size={20} />
                        Back to Home
                    </Link>
                </div>

                <h1 style={{
                    fontSize: '3rem',
                    fontWeight: '800',
                    marginBottom: '1rem',
                    background: 'linear-gradient(135deg, var(--accent), var(--accent-2))',
                    WebkitBackgroundClip: 'text',
                    WebkitTextFillColor: 'transparent'
                }}>WINST AI – Terms of Service</h1>

                <p style={{ color: 'var(--text-secondary)', marginBottom: '3rem' }}>Last Updated: [Insert Date]</p>

                <div className="terms-content" style={{ lineHeight: '1.8', fontSize: '1.05rem' }}>

                    <p className="mb-6" style={{ marginBottom: '1.5rem' }}>
                        These Terms of Service ("Terms") govern your access to and use of Winst AI, an artificial intelligence–powered analytics and insights platform operated by Conglorean Datalabs and Media Private Limited, a company registered under the laws of India ("Winst AI," "Company," "we," "us," or "our").
                    </p>
                    <p className="mb-6" style={{ marginBottom: '1.5rem' }}>
                        By accessing or using the Services, you agree to be bound by these Terms.
                        If you do not agree, you must not access or use Winst AI.
                    </p>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>1. Definitions</h2>
                    <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <li style={{ marginBottom: '0.5rem' }}><strong>"Services"</strong> means Winst AI's software, platform, websites, mobile applications, AI systems, analytics tools, token systems, advertising-supported features, APIs, documentation, and all related offerings.</li>
                        <li style={{ marginBottom: '0.5rem' }}><strong>"User," "you," or "Customer"</strong> means any individual or entity using the Services.</li>
                        <li style={{ marginBottom: '0.5rem' }}><strong>"AI Output"</strong> means any text, data, insights, graphs, predictions, or analytics generated by Winst AI based on User Input.</li>
                        <li style={{ marginBottom: '0.5rem' }}><strong>"User Input"</strong> means data provided by the User, including stock selections, text prompts, queries, or uploaded content.</li>
                        <li style={{ marginBottom: '0.5rem' }}><strong>"Tokens"</strong> refer to AI usage credits required to perform analyses within the platform.</li>
                        <li style={{ marginBottom: '0.5rem' }}><strong>"Third-Party Data Providers"</strong> means independent data sources used by Winst AI (including OpenAI and other APIs).</li>
                        <li style={{ marginBottom: '0.5rem' }}><strong>"Free User"</strong> refers to a User using the ad-supported free model.</li>
                        <li style={{ marginBottom: '0.5rem' }}><strong>"Premium User"</strong> refers to a User purchasing ads-free subscription plans or token packages.</li>
                    </ul>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>2. Eligibility</h2>
                    <div style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        You must:
                        <ul style={{ listStyleType: 'none', paddingLeft: '0', marginTop: '0.5rem' }}>
                            <li>(a) Be at least 18 years old,</li>
                            <li>(b) Have legal capacity to enter a binding agreement,</li>
                            <li>(c) Comply with these Terms.</li>
                        </ul>
                        <p style={{ marginTop: '1rem' }}>Winst AI is not for children under 13, and Users between 13–18 require parental consent.</p>
                    </div>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>3. Nature of the Service</h2>
                    <div style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        Winst AI:
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginTop: '0.5rem' }}>
                            <li style={{ marginBottom: '0.5rem' }}>Uses AI and third-party APIs to analyze historical stock market data (up to 30 years), fundamentals, financials, news, insider trades, and filings.</li>
                            <li style={{ marginBottom: '0.5rem' }}>Provides AI-generated analytics for educational and informational purposes only.</li>
                            <li style={{ marginBottom: '0.5rem' }}>Does not provide financial, investment, tax, or legal advice.</li>
                            <li style={{ marginBottom: '0.5rem' }}>Is not a broker, investment advisor, fiduciary, or financial advisor.</li>
                        </ul>
                    </div>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>4. No Investment Advice</h2>
                    <div style={{ padding: '1.5rem', backgroundColor: 'rgba(255, 107, 107, 0.1)', border: '1px solid rgba(255, 107, 107, 0.3)', borderRadius: '12px', marginBottom: '2rem' }}>
                        <strong style={{ color: 'var(--accent-3)', display: 'block', marginBottom: '1rem', fontSize: '1.1rem' }}>VERY IMPORTANT</strong>
                        <p style={{ marginBottom: '1rem', color: 'var(--text-primary)' }}>AI Output is not guaranteed to be accurate, may contain errors, and must not be relied upon for any investment decisions.</p>
                        <p style={{ marginBottom: '1rem', color: 'var(--text-primary)' }}>By using the platform, you acknowledge that:</p>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginBottom: '1rem', color: 'var(--text-primary)' }}>
                            <li>Winst AI is not responsible for investment losses.</li>
                            <li>Past performance is not indicative of future results.</li>
                            <li>You use the information at your own risk.</li>
                        </ul>
                    </div>

                    <div style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <p className="mb-4">Winst AI does not provide:</p>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem' }}>
                            <li>Personalized financial advice</li>
                            <li>Stock recommendations</li>
                            <li>Portfolio management</li>
                            <li>Fiduciary services</li>
                            <li>Predictions or guarantees of future performance</li>
                        </ul>
                        <p style={{ marginTop: '1rem' }}>You agree to consult a licensed financial advisor before making investment decisions.</p>
                    </div>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>5. Account Registration</h2>
                    <div style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <p>To use the Services, you must create an account. You agree to:</p>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginTop: '0.5rem' }}>
                            <li>Provide accurate registration information</li>
                            <li>Keep credentials confidential</li>
                            <li>Be responsible for activities under your account</li>
                            <li>Notify us of unauthorized access</li>
                        </ul>
                    </div>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>6. Token System</h2>
                    <div style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <h3 style={{ fontSize: '1.3rem', fontWeight: '600', marginBottom: '1rem', color: 'var(--text-primary)' }}>6.1 Free Token Allocation</h3>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginBottom: '1.5rem' }}>
                            <li>Upon successful registration, Users receive 50,000 free AI Tokens ("Welcome Tokens").</li>
                        </ul>

                        <h3 style={{ fontSize: '1.3rem', fontWeight: '600', marginBottom: '1rem', color: 'var(--text-primary)' }}>6.2 Earning Tokens Through Ads</h3>
                        <p>Free Users may watch advertisements to earn additional tokens.</p>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginBottom: '1.5rem' }}>
                            <li>Each ad view may award 1,500–2,000 Tokens, determined by Winst AI.</li>
                            <li>Token amounts may change without notice.</li>
                        </ul>

                        <h3 style={{ fontSize: '1.3rem', fontWeight: '600', marginBottom: '1rem', color: 'var(--text-primary)' }}>6.3 Purchasing Tokens & Premium Plans</h3>
                        <p>Premium Users may purchase:</p>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginBottom: '0.5rem' }}>
                            <li>Ads-free subscription plans</li>
                            <li>Token top-ups</li>
                        </ul>
                        <p>All payments are final and non-refundable except as required by law.</p>
                    </div>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>7. Ads & Monetization</h2>
                    <div style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <p>Free Users may see ads delivered by:</p>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginTop: '0.5rem', marginBottom: '1rem' }}>
                            <li>Winst AI</li>
                            <li>Third-party ad networks</li>
                            <li>Demand partners</li>
                        </ul>
                        <p>By using the free service, you consent to receiving ads. Premium Users will not see ads.</p>
                    </div>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>8. License & Use Rights</h2>
                    <div style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <p className="mb-4">We grant you a limited, non-exclusive, non-sublicensable, revocable license to access and use Winst AI for personal or internal business purposes.</p>
                        <p className="mb-2">You may not:</p>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem' }}>
                            <li>Resell or commercialize the AI Output</li>
                            <li>Attempt to extract or recreate Winst AI models</li>
                            <li>Scrape or harvest data</li>
                            <li>Misuse tokens or manipulate ad reward systems</li>
                            <li>Circumvent access limits</li>
                            <li>Reverse engineer the platform</li>
                            <li>Use AI Output to build competing AI models</li>
                            <li>Use bots, scripts, or automation to generate tokens or traffic</li>
                        </ul>
                    </div>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>9. Third-Party Data & APIs</h2>
                    <div style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <p>Winst AI uses multiple external data sources, including but not limited to:</p>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginTop: '0.5rem', marginBottom: '1rem' }}>
                            <li>OpenAI</li>
                            <li>Stock market data APIs</li>
                            <li>News databases</li>
                            <li>SEC filings</li>
                            <li>Sentiment engines</li>
                            <li>Financial analytics providers</li>
                        </ul>
                        <p>These sources may:</p>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginTop: '0.5rem', marginBottom: '1rem' }}>
                            <li>Contain inaccuracies</li>
                            <li>Change without notice</li>
                            <li>Impose their own licensing rules</li>
                        </ul>
                        <p>Winst AI is not responsible for third-party data quality, accuracy, outages, or reliability.</p>
                    </div>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>10. User Input & AI Output</h2>
                    <div style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <h3 style={{ fontSize: '1.3rem', fontWeight: '600', marginBottom: '1rem', color: 'var(--text-primary)' }}>10.1 Ownership</h3>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginBottom: '1.5rem' }}>
                            <li>You retain ownership of your User Input.</li>
                            <li>You are granted rights to use AI Output for personal or business analytics, subject to Third-Party Provider terms.</li>
                        </ul>

                        <h3 style={{ fontSize: '1.3rem', fontWeight: '600', marginBottom: '1rem', color: 'var(--text-primary)' }}>10.2 Data Use</h3>
                        <p>We may use User Input and AI Output to:</p>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginBottom: '0.5rem' }}>
                            <li>Operate and maintain the service</li>
                            <li>Comply with law</li>
                            <li>Ensure safety and prevent abuse</li>
                            <li>Improve system logic (never in a way that exposes personal data)</li>
                        </ul>
                        <p style={{ marginBottom: '1.5rem' }}>We do not sell User Input or personal data.</p>

                        <h3 style={{ fontSize: '1.3rem', fontWeight: '600', marginBottom: '1rem', color: 'var(--text-primary)' }}>10.3 Non-unique Output</h3>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem' }}>
                            <li>AI Output may be similar or identical for other users.</li>
                        </ul>
                    </div>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>11. Privacy</h2>
                    <p style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>Winst AI's Privacy Policy governs how we process your data.</p>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>12. Payments, Billing, Taxes</h2>
                    <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <li>Payments are processed by third-party processors (Stripe, Google Play Billing, Apple IAP, Razorpay, etc.).</li>
                        <li>Charges are non-refundable unless required by law.</li>
                        <li>Taxes may apply depending on your region.</li>
                        <li>Premium plans auto-renew unless cancelled.</li>
                    </ul>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>13. Prohibited Activities</h2>
                    <div style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <p>You may not use Winst AI for:</p>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginTop: '0.5rem' }}>
                            <li>Investment advice or portfolio management</li>
                            <li>Money laundering, fraud, or illegal activities</li>
                            <li>Automated trading systems</li>
                            <li>Generating misinformation</li>
                            <li>Unauthorized scraping, mining, or extraction</li>
                            <li>Reverse engineering or model extraction</li>
                            <li>Abusing ad-token systems</li>
                            <li>Violating US, Indian, or international sanctions laws</li>
                        </ul>
                    </div>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>14. Security</h2>
                    <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <li>We implement reasonable technical and organizational security measures.</li>
                        <li>However, no system is 100% secure, and you assume risk for transmitted data.</li>
                    </ul>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>15. Disclaimers</h2>
                    <div style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <p>Winst AI is provided "AS IS" and "AS AVAILABLE." We make no warranties regarding:</p>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginTop: '0.5rem' }}>
                            <li>Accuracy of AI Output</li>
                            <li>Data completeness</li>
                            <li>Uninterrupted service</li>
                            <li>Timeliness of analytics</li>
                            <li>Investment suitability</li>
                            <li>Third-party integrations</li>
                            <li>Token delivery or ads availability</li>
                        </ul>
                    </div>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>16. Limitation of Liability</h2>
                    <div style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <p>To the fullest extent permitted by law:</p>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginTop: '0.5rem' }}>
                            <li>Winst AI is not liable for any financial loss, investment loss, lost profits, loss of data, or indirect damages.</li>
                            <li>Our total liability will not exceed the amount you paid in the past 12 months.</li>
                        </ul>
                    </div>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>17. Indemnification</h2>
                    <div style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <p>You agree to indemnify and defend Winst AI from claims arising from:</p>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginTop: '0.5rem' }}>
                            <li>Your misuse of the Services</li>
                            <li>Violations of these Terms</li>
                            <li>Any investment decision you make</li>
                            <li>Non-compliance with applicable laws</li>
                            <li>Use of AI Output</li>
                        </ul>
                    </div>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>18. DMCA / Copyright Complaints</h2>
                    <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <li>Winst AI complies with the Digital Millennium Copyright Act.</li>
                        <li>Submit notices to: support@winstai.com</li>
                    </ul>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>19. Governing Law</h2>
                    <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <li>These Terms are governed by the laws of the State of Delaware, USA, without regard to conflict-of-law principles.</li>
                    </ul>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>20. Jurisdiction</h2>
                    <div style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <p><strong>Primary jurisdiction:</strong> Courts of Bangalore, Karnataka, India (For injunctions, enforcement, company disputes)</p>
                        <p style={{ marginTop: '0.5rem' }}><strong>Arbitration:</strong> United States (As described below)</p>
                    </div>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>21. Mandatory Arbitration & Class-Action Waiver</h2>
                    <div style={{ padding: '1.5rem', backgroundColor: 'rgba(255, 107, 107, 0.05)', border: '1px solid rgba(255, 107, 107, 0.2)', borderRadius: '12px', marginBottom: '2rem' }}>
                        <p style={{ fontWeight: '700', color: 'var(--accent-3)', marginBottom: '1rem' }}>YOU AGREE TO BINDING INDIVIDUAL ARBITRATION IN THE USA.</p>
                        <p style={{ fontWeight: '700', color: 'var(--accent-3)', marginBottom: '1rem' }}>YOU WAIVE THE RIGHT TO PARTICIPATE IN A CLASS ACTION.</p>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', color: 'var(--text-secondary)' }}>
                            <li>Arbitration will be administered by NAM (National Arbitration and Mediation) or a similar US forum.</li>
                            <li>Venue may be remote, virtual, or located in Delaware unless otherwise agreed.</li>
                            <li>Claims must be brought individually.</li>
                            <li>Class actions, collective actions, mass arbitrations, and representative actions are prohibited.</li>
                        </ul>
                        <p style={{ marginTop: '1rem', fontStyle: 'italic', color: 'var(--text-secondary)' }}>Certain claims (e.g., injunctions, IP issues) may be brought in Indian courts.</p>
                    </div>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>22. Termination</h2>
                    <div style={{ marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <p>We may suspend or terminate your account for:</p>
                        <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginTop: '0.5rem', marginBottom: '1rem' }}>
                            <li>Violating the Terms</li>
                            <li>Abusing tokens or ads</li>
                            <li>Fraudulent activities</li>
                            <li>Legal compliance requirements</li>
                            <li>Inactivity over prolonged periods</li>
                        </ul>
                        <p>You may terminate your account any time.</p>
                    </div>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>23. Modifications</h2>
                    <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginBottom: '1.5rem', color: 'var(--text-secondary)' }}>
                        <li>Winst AI may update these Terms with notice.</li>
                        <li>Continued use of the Services constitutes acceptance.</li>
                    </ul>

                    <h2 style={{ fontSize: '1.8rem', fontWeight: '700', marginTop: '3rem', marginBottom: '1.5rem', color: 'var(--text-primary)' }}>24. Miscellaneous</h2>
                    <ul style={{ listStyleType: 'disc', paddingLeft: '1.5rem', marginBottom: '3rem', color: 'var(--text-secondary)' }}>
                        <li>These Terms constitute the entire agreement.</li>
                        <li>If any provision is unenforceable, it will be modified as necessary.</li>
                        <li>You may not assign your rights without consent.</li>
                        <li>We may assign this Agreement to affiliates or successors.</li>
                    </ul>
                </div>
            </div>
        </div>
    );
};

export default TermsOfService;
